### ISSUE TITLE
Java Websocket client throws IO exception due to error shown below when broker closes the connection

### ISSUE THREAD

**Issue by jpwsutton** [eclipse-paho/paho.mqtt.java#177]
Moved from Android Project Issue https://github.com/eclipse/paho.mqtt.android/issues/1
Java Websocket client throws IO exception due to error shown below when broker closes the connection. This is observed on the development branch org.eclipse.paho.client.mqttv3-1.0.3-SNAPSHOT.jar. Some details are included in this thread https://www.eclipse.org/forums/index.php/t/1075009/

Publishing at: 2016-02-22 22:59:03.496 to topic "mqtt/demo" qos 2
WebSocketReceiver.java : run(): Exception Occured.
java.io.IOException: Invalid Frame: Opcode: 15
at org.eclipse.paho.client.mqttv3.internal.websocket.WebSocketFrame.(WebSocketFrame.java:187)
at org.eclipse.paho.client.mqttv3.internal.websocket.WebSocketReceiver.run(WebSocketReceiver.java:98)
at java.lang.Thread.run(Thread.java:745)
Disconnected

**Comment by jpwsutton** [comment]
Resolved by PR #192
