### ISSUE TITLE
NPE possibly caused by race condition in isConnected()

### ISSUE THREAD

**Issue by upost** [eclipse-paho/paho.mqtt.java#189]
Good morning,

in a heavily used android app, I observe the following NPE several times a day in user reports:

`java.lang.RuntimeException: Error receiving broadcast Intent { act=android.net.conn.CONNECTIVITY_CHANGE flg=0x4000010 (has extras) } in
org.eclipse.paho.android.service.MqttService$NetworkConnectionIntentReceiver@2a97f1fe
    at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:882)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:211)
    at android.app.ActivityThread.main(ActivityThread.java:5373)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.net.NetworkInfo.isConnected()' on a null object reference
    at org.eclipse.paho.android.service.MqttService.isOnline(MqttService.java:814)
    at org.eclipse.paho.android.service.MqttService$NetworkConnectionIntentReceiver.onReceive(MqttService.java:796)
    at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:872)
    ... 8 more`

Only possible reason seems to be that cm.getActiveNetworkInfo() becomes null inside the if condition in MqttService.isOnline() just after the check if it isn't. As I experienced similar behaviour in other Android services, I suggest the following change to isOnline():

`NetworkInfo networkInfo = cm.getActiveNetworkInfo();
if (networkInfo != null
                && networkInfo.isAvailable()
                && networkInfo.isConnected()
                && backgroundDataEnabled) {
            return true;
}`

Or do I miss something else?

**Comment by jpwsutton** [comment]
@upost I believe that this change has already been made in the develop version of the client (https://github.com/eclipse/paho.mqtt.android/blob/master/org.eclipse.paho.android.service/src/main/java/org/eclipse/paho/android/service/MqttService.java#L820). Is this what you mean?

You can currently get this fixed version by switching to the SNAPSHOT library.

**Comment by jpwsutton** [comment]
This issue was moved to eclipse/paho.mqtt.android#83
