### ISSUE TITLE
Enabling proguard with mqttv3 java client

### ISSUE THREAD

**Issue by Nishant-Pathak** [eclipse-paho/paho.mqtt.java#190]
Hi all,

While building java client for mqtt broker, it works good unless I try to build my project with proguard maven plugin. I am getting below error. Please tell if I missed something in my proguard-rules or any specific rule to be added.

```
 [proguard]   Exception   = [java.lang.IllegalArgumentException] (Can't find common super class of [org/eclipse/paho/client/mqttv3/internal/SSLNetworkModule] (with 2 known super classes) and [org/eclipse/paho/client/mqttv3/internal/LocalNetworkModule] (with 1 known super classes))
 [proguard] java.lang.IllegalArgumentException: Can't find common super class of [org/eclipse/paho/client/mqttv3/internal/SSLNetworkModule] (with 2 known super classes) and [org/eclipse/paho/client/mqttv3/internal/LocalNetworkModule] (with 1 known super classes)
 [proguard]     at proguard.evaluation.value.TypedReferenceValue.findCommonClass(TypedReferenceValue.java:441)
 [proguard]     at proguard.evaluation.value.TypedReferenceValue.generalize(TypedReferenceValue.java:277)
 [proguard]     at proguard.evaluation.value.TypedReferenceValue.generalize(TypedReferenceValue.java:201)
 [proguard]     at proguard.evaluation.value.ReferenceValue.generalize(ReferenceValue.java:298)
 [proguard]     at proguard.evaluation.Variables.generalize(Variables.java:136)
 [proguard]     at proguard.evaluation.TracedVariables.generalize(TracedVariables.java:118)
 [proguard]     at proguard.optimize.evaluation.PartialEvaluator.evaluateSingleInstructionBlock(PartialEvaluator.java:689)
 [proguard]     at proguard.optimize.evaluation.PartialEvaluator.evaluateInstructionBlock(PartialEvaluator.java:608)
 [proguard]     at proguard.optimize.evaluation.PartialEvaluator.evaluateInstructionBlockAndExceptionHandlers(PartialEvaluator.java:566)
 [proguard]     at proguard.optimize.evaluation.PartialEvaluator.visitCodeAttribute0(PartialEvaluator.java:270)
 [proguard]     at proguard.optimize.evaluation.PartialEvaluator.visitCodeAttribute(PartialEvaluator.java:187)
 [proguard]     at proguard.classfile.attribute.CodeAttribute.accept(CodeAttribute.java:101)
 [proguard]     at proguard.classfile.ProgramMethod.attributesAccept(ProgramMethod.java:79)
 [proguard]     at proguard.classfile.attribute.visitor.AllAttributeVisitor.visitProgramMember(AllAttributeVisitor.java:95)
 [proguard]     at proguard.classfile.util.SimplifiedVisitor.visitProgramMethod(SimplifiedVisitor.java:92)
 [proguard]     at proguard.classfile.ProgramMethod.accept(ProgramMethod.java:71)
 [proguard]     at proguard.classfile.ProgramClass.methodsAccept(ProgramClass.java:504)
 [proguard]     at proguard.classfile.visitor.AllMethodVisitor.visitProgramClass(AllMethodVisitor.java:47)
 [proguard]     at proguard.classfile.visitor.ClassAccessFilter.visitProgramClass(ClassAccessFilter.java:67)
 [proguard]     at proguard.classfile.ProgramClass.accept(ProgramClass.java:346)
 [proguard]     at proguard.classfile.ClassPool.classesAccept(ClassPool.java:124)
 [proguard]     at proguard.optimize.Optimizer.execute(Optimizer.java:445)
 [proguard]     at proguard.ProGuard.optimize(ProGuard.java:317)
 [proguard]     at proguard.ProGuard.execute(ProGuard.java:126)
 [proguard]     at proguard.ProGuard.main(ProGuard.java:507)
```

**Comment by nisrulz** [comment]
try adding rules to your `proguard-rules.pro` file 

```
-keep class class org.eclipse.paho.client.mqttv3.* { *; }
-keep class class org.eclipse.paho.client.mqttv3.*$* { *; }
```

**Comment by Amezing** [comment]
sometimes conneted mqttserver successed received a message but to MqttPingSender.stop()?

**Comment by jpwsutton** [comment]
I think this question has been answered by @nisrulz (Thank you), so I'm going to close it.
