### ISSUE TITLE
Mqtt connection exceptions

### ISSUE THREAD

**Issue by milosjovac** [eclipse-paho/paho.mqtt.java#309]
- [ YES ] Bug exists Release Version 1.1.0 ( Master Branch)
- [ YES ] Bug exists in Snapshot Version 1.1.1-SNAPSHOT (Develop Branch)

I have noticed two very frequent exceptions in the past few weeks.

SocketTimeoutException:

`MqttException (0) - java.net.SocketTimeoutException: connect timed out
	at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:38)
	at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:690)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.net.SocketTimeoutException: connect timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.connect(Unknown Source)
	at org.eclipse.paho.client.mqttv3.internal.TCPNetworkModule.start(TCPNetworkModule.java:81)
	at org.eclipse.paho.client.mqttv3.internal.SSLNetworkModule.start(SSLNetworkModule.java:92)
	at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:676)`

EOFException:

`Connection lost (32109) - java.io.EOFException
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:155)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.io.EOFException
	at java.io.DataInputStream.readByte(Unknown Source)
	at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:92)
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:113)`

My MQTT connection options:

            MemoryPersistence persistence = new MemoryPersistence();
            mqttClient = new MqttClient(dip.getBrokerUrl(), clientId, persistence);
            mqttClient.setCallback(getMqttCallback());

            // Setting up SSLSocketFactory
            sc = SSLContext.getInstance("TLSv1");
            sc.init(null, null, null);
            ssf = sc.getSocketFactory();
    
            // Setting up ConnectionOptions
            connOpts = new MqttConnectOptions();
            connOpts.setMaxInflight(200);
            // I tried with a different connectionTimeout and keepAliveInterval values but errors persist, so it is left to default
            //connOpts.setConnectionTimeout(10);
            //connOpts.setKeepAliveInterval(31); 
            connOpts.setAutomaticReconnect(false);
            connOpts.setCleanSession(true);
            connOpts.setSocketFactory(ssf);
 
            mqttClient.connect(connOpts);

Client is running 24/7, and in the moment of catching exceptions I'm checking if there is an Internet connection. And yes, client is connected to the router via LAN, and Internet connection is reachable. EOFException is way less frequent but it is always present in logs. 

To check for Internet connection I'm using the following code:

        public static boolean isInternetConnectionAvailable() {
            Process p1 = null;
             try {
                p1 = Runtime.getRuntime().exec("ping -c 1 www.google.com");
                int returnVal = p1.waitFor();
                return returnVal == 0;
            } catch (IOException e) {
                e.printStackTrace();
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
            return false;
        }

I saw some issues regarding Socket Timeout here in [issue tracker](https://github.com/eclipse/paho.mqtt.java/issues?utf8=%E2%9C%93&q=is%3Aissue%20Socket%20Timeout%20) ,  and all of the problems are marked as resolved atm, at least for the dev branch. However I'm experiencing this exceptions on both, stable and snapshoot version of the library (snapshoot built from the source on Dec.07.2016.).

It seems to me as a bug, but can be that I'm doing something wrong?

**Comment by jpwsutton** [comment]
Hi @milosjovac, out of interest, what type / version of MQTT broker are you using? Also, whilst I can't claim that it is the cause of your issues, but TLSv1 is definitely not recommended..

**Comment by milosjovac** [comment]
Hi @jpwsutton,

- MQTT broker in use is mosquitto version 1.4.10 
- Will try with TLSv1.2 and see if there are any changes

**Comment by jpwsutton** [comment]
Hi @milosjovac, did you find using TLSv1.2 fixed your problem?

**Comment by milosjovac** [comment]
Hi @jpwsutton 

- It seems as it helped actually. First exception disappeared after the change.

- For the second exception, problem was the same name for multiple mqtt clients. Clients with the same name will race for connection and kick each other from the broker. We have unique name per hosting device, but during update process there was a window of couple of minutes where two clients with the same name were running simultaneously (old and new version).
