### ISSUE TITLE
no new message IDs being available with QoS 0

### ISSUE THREAD

**Issue by xboss** [eclipse-paho/paho.mqtt.java#323]
- [x] Bug exists Release Version 1.1.0 ( Master Branch)
- [ ] Bug exists in Snapshot Version 1.1.1-SNAPSHOT (Develop Branch)

Log:
Internal error, caused by no new message IDs being available (32001)
        at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:31)
        at org.eclipse.paho.client.mqttv3.internal.ClientState.getNextMessageId(ClientState.java:1252)
        at org.eclipse.paho.client.mqttv3.internal.ClientState.send(ClientState.java:481)
        at org.eclipse.paho.client.mqttv3.internal.ClientComms.internalSend(ClientComms.java:114)
        at org.eclipse.paho.client.mqttv3.internal.ClientComms.sendNoWait(ClientComms.java:138)
        at org.eclipse.paho.client.mqttv3.MqttAsyncClient.publish(MqttAsyncClient.java:1027)
        at org.eclipse.paho.client.mqttv3.MqttAsyncClient.publish(MqttAsyncClient.java:991)

Publish in a large number of qos0 messages, it is possible to report this error,
I feel inUseMsgIds this map no release msgId.
paho mqtt version is  1.1.0

**Comment by jpwsutton** [comment]
Hi @xboss 

Could you test this out using the 1.1.1-SNAPSHOT version please?

I've tested this myself using the latest snapshot and was not able to re-create your issue.

For reference, I ran the following code that attempted to send 70,000 messages which would have pushed the message ID past the limit of 65535;

```
 public static void main( String[] args )
    {

      String topic        = "issue_323";
        String content      = "Message from MqttPublishSample";
        int qos             = 0;
        String broker       = "tcp://localhost";
        String clientId     = "testing_issue_323";
        MemoryPersistence persistence = new MemoryPersistence();

        try {
            MqttClient sampleClient = new MqttClient(broker, clientId, persistence);
            MqttConnectOptions connOpts = new MqttConnectOptions();
            connOpts.setCleanSession(true);
            System.out.println("Connecting to broker: "+broker);
            sampleClient.connect(connOpts);
            System.out.println("Connected");
            System.out.println("Publishing message: "+content);
            
            // Send 70000 message (more than the 65535 limit)
            for(int i = 0; i < 70000; i++){
            	String msg = content + "number: " + i;
            	MqttMessage message = new MqttMessage(msg.getBytes());
                message.setQos(qos);
            	sampleClient.publish(topic, message);
                System.out.println("Message published : "  + i);
            }
            
            sampleClient.disconnect();
            System.out.println("Disconnected");
            System.exit(0);
        } catch(MqttException me) {
            System.out.println("reason "+me.getReasonCode());
            System.out.println("msg "+me.getMessage());
            System.out.println("loc "+me.getLocalizedMessage());
            System.out.println("cause "+me.getCause());
            System.out.println("excep "+me);
            me.printStackTrace();
        }
    }
```

Matching subscription verifying delivery:

```
issue_323 Message from MqttPublishSamplenumber: 69995
issue_323 Message from MqttPublishSamplenumber: 69996
issue_323 Message from MqttPublishSamplenumber: 69997
issue_323 Message from MqttPublishSamplenumber: 69998
issue_323 Message from MqttPublishSamplenumber: 69999
```

By passing the 65535 limit, you can see that the message IDs are definitely being released.

I wonder if this could be an implementation / volume issue. How many QoS 0 messages are you attempting to send? How quickly are you attempting to send them?

**Comment by xboss** [comment]
It happens in our online environment, so we didn't test 1.1.1-SNAPSHOT
and we have used MqttAsyncClient.
About 100~500 messages per second.
Is this problem related to concurrency?

My English is not good，I'm not sure that u can understand me or not.
thanks a lot

**Comment by jpwsutton** [comment]
Hi @xboss, sorry for the delay. What server are you using?

**Comment by chbest-btc** [comment]
Hi

is there a solution for this problem?

I am using the paho version 1.2.0 together with a RabbitMQ 3.6.12 under Fedora 26 and I am getting the following exception:


```
Internal error, caused by no new message IDs being available (32001)
java.lang.RuntimeException: Internal error, caused by no new message IDs being available (32001)
	at com.btc.sdsp.streamgenerator.App.sendMessage(App.java:74)
	at com.btc.sdsp.streamgenerator.App.sendMessages(App.java:58)
	at com.btc.sdsp.streamgenerator.App$1.onSuccess(App.java:29)
	at org.eclipse.paho.client.mqttv3.internal.ConnectActionListener.onSuccess(ConnectActionListener.java:99)
	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.fireActionEvent(CommsCallback.java:321)
	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.handleActionComplete(CommsCallback.java:260)
	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.run(CommsCallback.java:190)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Till then 65535 messages have been send to the server.

I want to send 5,000 messages per second to the RabbitMQ and try to achieve that by the following code:


```
public class App {
    public static void main(String[] args) throws MqttException, InterruptedException {
        connectAndSend();
    }

    public static void connectAndSend() throws MqttException, InterruptedException {
        MqttAsyncClient client = new MqttAsyncClient("tcp://localhost:1883", MqttClient.generateClientId(),
                null, new TimerPingSender(), Executors.newScheduledThreadPool(100) );
        MqttConnectOptions options = new MqttConnectOptions();
        options.setMaxInflight(100000);
        options.setWill(
                "will/topic",               //Topic
                "Disconnected!".getBytes(), //Nachrichteninhalt
                0,      //QoS
                false); //Retained message?

        client.connect(options, null, new MqttAsyncActionListener() {
            public void onSuccess(IMqttToken asyncActionToken) {
                try {
                    sendMessages(client, 100, 0, 100000, 5000, 1000);
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }

            public void onFailure(IMqttToken asyncActionToken, Throwable exception) {
                exception.printStackTrace();
            }
        });

    }

    private static class MqttAsyncActionListener implements IMqttActionListener {

        @Override
        public void onSuccess(IMqttToken asyncActionToken) {

        }

        @Override
        public void onFailure(IMqttToken asyncActionToken, Throwable exception) {

        }
    }

    public static void sendMessages(final MqttAsyncClient client, int MessageSize, int StartNumber, int EndNumber, int NumberOfMessagesPerIntervall, int IntervallTimeInMiliseconds) throws MqttException, InterruptedException {
        for (int i = 0; i < EndNumber / NumberOfMessagesPerIntervall; i++) {
            for (int j = 0; j < NumberOfMessagesPerIntervall; j++) {
                sendMessage(client);
            }
            Thread.sleep(IntervallTimeInMiliseconds);
        }
        for (int i=0;i<(EndNumber%NumberOfMessagesPerIntervall);i++) {
            sendMessage(client);
        }
    }

    public static void sendMessage(final MqttAsyncClient client) {
        final MqttMessage message = new MqttMessage();
        message.setPayload("Hello world from Java".getBytes());
        try {
            client.publish("TopicA", message);
        } catch (MqttException e) {
            System.out.println(e);
            throw new RuntimeException(e);
        }
    }
}
```


Is there a way to avoid the exception?

**Comment by Odyldzhon** [comment]
I have similar issue and the root cause was related to difference between publisher QOS and subscriber QOS.
If a client is subscribed with QoS 2 and a message is published on QoS 0, the client will receive it on QoS 0. But in my case I expect that QOS will be similar to subscription QOS i.e. 2 and send manual acknowledgement using QOS 2 which assumed a response from MQTT Broker and this response was never come to the subscriber and this is why the message IDs were slowly used until limit.

The fix is simple, just use QOS of incoming message for acknowledgement.
