### ISSUE TITLE
at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:650) 03-17 18:07:57.651 28073-29356/com.workforce.agent W/System.err:     at org.eclipse.paho.client.mqttv3.internal.TCPNetworkModule.start(TCPNetworkModule.java:70)

### ISSUE THREAD

**Issue by DavidMont** [eclipse-paho/paho.mqtt.java#342]
- [x] Bug exists Release Version 1.1.0 ( Prev-Master Branch)
- [x] Bug exists Release Version 1.1.1 ( Master Branch)
at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:650)
03-17 18:07:57.651 28073-29356/com.workforce.agent W/System.err:     at org.eclipse.paho.client.mqttv3.internal.TCPNetworkModule.start(TCPNetworkModule.java:70)

When I toggle the wifi or data plan from on to off to on again the problem will exist.

**Comment by jpwsutton** [comment]
Hi, before we can take a look at this, could you check if this bug exists in the snapshot builds from the develop branch, and also provide an actual stack trace of the error.

**Comment by DavidMont** [comment]
do you mean testing for v1.1.1? other than that is it ok to ask if there si change between here ```TCPNetworkModule.java:70``` ?

**Comment by DavidMont** [comment]
I replicated the issue on version 3 1.1.1, but will test again on development branch

**Comment by DavidMont** [comment]
Happens when still connecting but the app(android app ) is closed AND cant connect to internet, and when trying to connect again 
```java 
mClient.connect()
```  

`org.eclipse.paho.client.mqttv3.internal.TCPNetworkModule.start(TCPNetworkModule.java:70)` endless loop of error occurs when it should behave to just do nothing when it cannot connect.

**Comment by jpwsutton** [comment]
Ah, are you using the Android library? or the pure Java client for this?

**Comment by DavidMont** [comment]
the pure java client.

**Comment by jpwsutton** [comment]
Could you enable logging and capture logs covering this event please? https://wiki.eclipse.org/Paho/Log_and_Debug_in_the_Java_client

**Comment by jpwsutton** [comment]
Closing as we've had no response since March 2017

**Comment by dokiKit** [comment]
Can be reproduced in android lib in the same situation, where wifi is turn-off then on 
```
   implementation 'org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.1.0'
   implementation 'org.eclipse.paho:org.eclipse.paho.android.service:1.1.1'
```
```
2018-10-03 10:48:10.110 D/MqttManager: Connect Fail
2018-10-03 10:48:10.127 W/System.err:     at org.eclipse.paho.client.mqttv3.internal.TCPNetworkModule.start(TCPNetworkModule.java:79)
2018-10-03 10:48:10.127 W/System.err:     at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:650)
2018-10-03 10:48:10.130 W/System.err:     at org.eclipse.paho.client.mqttv3.internal.TCPNetworkModule.start(TCPNetworkModule.java:70)

```

**Comment by dokiKit** [comment]
more logs
```
2018-10-03 11:13:57.947 W/System.err: Unable to connect to server (32103) - java.net.ConnectException: Connection refused
2018-10-03 11:13:57.947 W/System.err:     at org.eclipse.paho.client.mqttv3.internal.TCPNetworkModule.start(TCPNetworkModule.java:79)
2018-10-03 11:13:57.947 W/System.err:     at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:650)
2018-10-03 11:13:57.947 W/System.err:     at java.lang.Thread.run(Thread.java:761)
2018-10-03 11:13:57.947 W/System.err: Caused by: java.net.ConnectException: Connection refused
2018-10-03 11:13:57.948 W/System.err:     at java.net.PlainSocketImpl.socketConnect(Native Method)
2018-10-03 11:13:57.948 W/System.err:     at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:334)
2018-10-03 11:13:57.948 W/System.err:     at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:196)
2018-10-03 11:13:57.948 W/System.err:     at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
2018-10-03 11:13:57.948 W/System.err:     at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:356)
2018-10-03 11:13:57.948 W/System.err:     at java.net.Socket.connect(Socket.java:605)
2018-10-03 11:13:57.948 W/System.err:     at org.eclipse.paho.client.mqttv3.internal.TCPNetworkModule.start(TCPNetworkModule.java:70)
2018-10-03 11:13:57.948 W/System.err: 	... 2 more
2018-10-03 11:13:57.948 D/MqttManager: Connect Fail
2018-10-03 11:13:57.968 W/System.err: Unable to connect to server (32103) - java.net.ConnectException: Connection refused
2018-10-03 11:13:57.969 W/System.err:     at org.eclipse.paho.client.mqttv3.internal.TCPNetworkModule.start(TCPNetworkModule.java:79)
2018-10-03 11:13:57.969 W/System.err:     at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:650)
2018-10-03 11:13:57.969 W/System.err:     at java.lang.Thread.run(Thread.java:761)
2018-10-03 11:13:57.969 W/System.err: Caused by: java.net.ConnectException: Connection refused
2018-10-03 11:13:57.969 W/System.err:     at java.net.PlainSocketImpl.socketConnect(Native Method)
2018-10-03 11:13:57.969 W/System.err:     at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:334)
2018-10-03 11:13:57.969 W/System.err:     at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:196)
2018-10-03 11:13:57.969 W/System.err:     at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
2018-10-03 11:13:57.969 W/System.err:     at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:356)
2018-10-03 11:13:57.969 W/System.err:     at java.net.Socket.connect(Socket.java:605)
2018-10-03 11:13:57.969 W/System.err:     at org.eclipse.paho.client.mqttv3.internal.TCPNetworkModule.start(TCPNetworkModule.java:70)
2018-10-03 11:13:57.969 W/System.err: 	... 2 more
```

**Comment by jpwsutton** [comment]
The exception is clearly saying that the connection was refused by the server. I suggest that you check that the server is running and that there is an open port in your firewall between the client and server.
