### ISSUE TITLE
Maximum size of MqttMessage 

### ISSUE THREAD

**Issue by agallojr** [eclipse-paho/paho.mqtt.java#359]
Please fill out the form below before submitting, thank you!
- [x ] Bug exists Release Version 1.1.0 ( Master Branch)
- [x ] Bug exists Release Version 1.1.1 ( Master Branch)
- [ ] Bug exists in Snapshot Version 1.1.2-SNAPSHOT (Develop Branch)

Using commonly available Paho demo code (attached), I iterate to find the maximum size of an MqttMessage to be 8076 bytes.  Have confirmed this on 1.1.0 and 1.1.1.  This is well below the theoretical limit of MQTT.  Need a way to surpass this 8k limit.    

[MqttTest.zip](https://github.com/eclipse/paho.mqtt.java/files/948323/MqttTest.zip)

reason 32109
msg Connection lost
loc Connection lost
cause java.io.EOFException
excep Connection lost (32109) - java.io.EOFException
Connection lost (32109) - java.io.EOFException
        at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:164)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.EOFException
        at java.io.DataInputStream.readByte(DataInputStream.java:267)
        at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:92)
        at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:116)

**Comment by agallojr** [comment]
After using multiple MQTT servers with the same Paho client and getting different results as to the maximum size of the MQTT payload, I think its safe to close this bug report on the basis of inaccuracy.  Thanks for listening.
