### ISSUE TITLE
Is there a way to set an expiration time for the inflight messages?

### ISSUE THREAD

**Issue by barbaragomes** [eclipse-paho/paho.mqtt.java#398]
Hi there,

I have been looking for a solution to my problem for a long time. My apologies if that is not the right place to ask.

I'm using Java Paho MQTT client in my application and I have set the maximum inflight messages to 15 and I'm publishing messages using qos 1.

The problem that I'm having is that sometimes the broker is dropping the messages and therefore is not sending an acknowledgement to the client, which keeps the dropped message in the inflight queue and will keep it forever since it will not be able to get the acknowledgement from the broker.

When I reach 15 messages in this situation, my client stops publishing because it is waiting for the acknowledgement that it will never receive.

Is there a way to set a expiration time to the inflight messages so my client does not hang in this situation?

**Comment by jpwsutton** [comment]
Hi @barbaragomes,

So the way that I would do this would be to use `getPendingDeliveryTokens` to get an array of all pending Delivery tokens, then calling `waitForCompletion` (This will block) with your chosen timeout. If the timeout passes without the message being delivered, it will throw an `MqttException` which you will have to handle. 

Once this has happened, you'll know that a message has not yet sent (At this point it may still complete even though the Exception has been thrown). But if you are using our SNAPSHOT build, you should be able to use a new enhancement with `removeMessage` which should remove the message from the outbound queue.

```
IMqttDeliveryToken[] tokens = sampleClient.getPendingDeliveryTokens();
try {
    tokens[0].waitForCompletion(1000);
} catch (MqttException ex) {
    // Message failed to send within a second
    sampleClient.removeMessage(tokens[0]);
}
```
Hopefully that should do the trick!

**Comment by barbaragomes** [comment]
@jpwsutton Thank you very much for your response. It works perfectly.

I have another issue going on now.

The problem that I'm having is that the disconnect callback is not being called when the client detects the connection lost while it is trying to publish.

I have an unstable internet connection and the following code for publishing:
```scala
if(pub != null && pub.isConnected) {
   try {
      val message = new MqttMessage(Message.getBytes("utf-8"))
      message.setQos(1)
      val token = pub.publish(topic, message)
    } catch {
      case e: Exception => log.error(e, "MQTT send Exception")
    }
}else{
   log.info("Client not connected")
}
```

The code passes the if part, where it checks if my publisher is connected, but when it tries to publish the message, it looses connection and gets in the catch part, logging the following:

```
org.eclipse.paho.client.mqttv3.MqttException: Connection lost
at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:181)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.EOFException: null
at java.io.DataInputStream.readByte(DataInputStream.java:267)
at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:92)
at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:133)
```

The problem is that the disconnect callback never gets called even thought the client is not connected anymore.

Is it a normal behavior?

P.S. Let me know if I should open a different thread for this issue.
