### ISSUE TITLE
Disconnection upon subscribing to # channel

### ISSUE THREAD

**Issue by zerogvt** [eclipse-paho/paho.mqtt.java#4]
Hi,
I see client disconnections upon subscription to # channel on an Apache Apollo broker.

Disconnection exception is: 

``````
 MqttException null
MqttException (0) - java.io.EOFException
    at org.eclipse.paho.client.mqttv3.internal.wire.MqttWireMessage.decodeUTF8(MqttWireMessage.java:344)
    at org.eclipse.paho.client.mqttv3.internal.wire.MqttPublish.<init>(MqttPublish.java:62)
    at org.eclipse.paho.client.mqttv3.internal.wire.MqttWireMessage.createWireMessage(MqttWireMessage.java:189)
    at org.eclipse.paho.client.mqttv3.internal.wire.MqttWireMessage.createWireMessage(MqttWireMessage.java:163)
    at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:83)
    at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:107)
    at java.lang.Thread.run(Thread.java:785)
Caused by: java.io.EOFException
    at java.io.DataInputStream.readFully(DataInputStream.java:208)
    at java.io.DataInputStream.readFully(DataInputStream.java:180)
    at org.eclipse.paho.client.mqttv3.internal.wire.MqttWireMessage.decodeUTF8(MqttWireMessage.java:340)
    ... 6 more```
``````

**Comment by jpwsutton** [comment]
Hi @winglet, I just set up an instance of the Apollo broker on my machine and subscribed to # using the SNAPSHOT version successfully. Could it be a configuration issue on your broker?

**Comment by zerogvt** [comment]
Hi,
unfortunately I'm not working on that anymore but one of the last things I saw was that the disconnection was triggered when trying trying JSON parsing of non JSON objects. This happened to coincide with the subscription to # channels which is why I thought there was a problem with that.

**Comment by jpwsutton** [comment]
Agreed, looks like expected behaviour when attempting to publish something that cannot be decoded properly
