### ISSUE TITLE
Cannot run my code with command line.

### ISSUE THREAD

**Issue by lonelyzerg** [eclipse-paho/paho.mqtt.java#437]
- [x] Bug exists Release Version 1.2.0 ( Master Branch)
- [ ] Bug exists in Snapshot Version 1.2.1-SNAPSHOT (Develop Branch)

Hi, I wrote a program using mqtt, and it runs well under Eclipse IDE. But when I try to run the code under command line it gives following errors. 
```
Exception in thread "Thread-0" Exception in thread "main" java.lang.NoClassDefFoundError: org/bytedeco/javacv/FFmpegFrameGrabber
	at Subscriber$showimg.run(Subscriber.java:100)
Caused by: java.lang.ClassNotFoundException: org.bytedeco.javacv.FFmpegFrameGrabber
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 1 more
java.lang.NoClassDefFoundError: org/eclipse/paho/client/mqttv3/MqttCallback
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at Subscriber.<init>(Subscriber.java:54)
	at Subscriber.main(Subscriber.java:68)
Caused by: java.lang.ClassNotFoundException: org.eclipse.paho.client.mqttv3.MqttCallback
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 14 more

```
Anyone know what caused this?

I am sorry, the problem lies in commands I used to run the program.

**Comment by Talles71** [comment]
anyone?
