### ISSUE TITLE
SSLSocket is not closed when disconnected from the broker

### ISSUE THREAD

**Issue by Akira1Saitoh** [eclipse-paho/paho.mqtt.java#467]
Hi,
Our project uses the paho in the unstable network conditions. We sometimes get the broker unreachable for a few minutes.
If the broker is unreachable for a long time, the connection to the broker is closed when the keepAliveInterval timeout expires, but the underlying socket is not closed if it is SSLSocket.

In `TCPNetworkModule#stop`, `shutdownInput` is called before `close`. However, if the socket is a SSLSocket, `close` is never called since `shutdownInput` always throws `UnsupportedOperationException`.
```
public void stop() throws IOException {
	if (socket != null) {
		// CDA: an attempt is made to stop the receiver cleanly before closing the socket.
		...
		// want to move it in SSLNetworkModule.

		socket.shutdownInput();
		socket.close();
	}
```

The netstat log shows that the old tcp connection is still alive even after the reconnect cycle has begun.
```
pi@8e65eabebd90:~/work$ netstat -ant
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp6       0  11479 172.17.0.2:46858        184.172.124.189:8883    ESTABLISHED
tcp6       0      1 172.17.0.2:46860        184.172.124.189:8883    SYN_SENT
```

- [x] Bug exists Release Version 1.2.0 ( Master Branch)
- [x] Bug exists in Snapshot Version 1.2.1-SNAPSHOT (Develop Branch)
- [?] Bug exists in MQTTv5 Version (mqttv5-new Branch)

**Comment by Akira1Saitoh** [comment]
I sometimes observe a deadlock between `MQTT Call` and `MQTT Snd` while disconnecting from the broker on keepAliveInterval timeout.
If our application tries to publish messages large enough to make the socket buffer full while the broker is unreachable, `MQTT Snd` blocks on write to the socket.
If keepAliveInterval timeout expires in that situation, `MQTT Call` thread waits inside `ClientState#resolveOldTokens` for the lock held by `MQTT Snd`, which does not return from write.

Attached archive contains a simple program to reproduce the deadlock, a thread dump, and logs. To simulate the network failure, I used iptables to drop all traffics from/to port 8883.
If the socket is closed properly, the deadlock will not occur because `MQTT Snd` will return from write.

[DisconnectByKeepAliveTimeoutSSLTest.tar.gz](https://github.com/eclipse/paho.mqtt.java/files/1624717/DisconnectByKeepAliveTimeoutSSLTest.tar.gz)

**Comment by plentz** [comment]
Also reported when using StrictMode

```
02-21 00:44:21.651  1459  1469 E StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
02-21 00:44:21.651  1459  1469 E StrictMode: java.lang.Throwable: Explicit termination method 'close' not called
02-21 00:44:21.651  1459  1469 E StrictMode: 	at dalvik.system.CloseGuard.open(CloseGuard.java:184)
02-21 00:44:21.651  1459  1469 E StrictMode: 	at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:316)
02-21 00:44:21.651  1459  1469 E StrictMode: 	at org.eclipse.paho.client.mqttv3.internal.SSLNetworkModule.start(SSLNetworkModule.java:97)
02-21 00:44:21.651  1459  1469 E StrictMode: 	at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:676)
02-21 00:44:21.651  1459  1469 E StrictMode: 	at java.lang.Thread.run(Thread.java:818)
```
StrictMode config

```java
StrictMode.setVmPolicy(new StrictMode.VmPolicy.Builder()
        .detectLeakedClosableObjects()
        .penaltyLog()
        .penaltyDeath()
        .build());
```
