### ISSUE TITLE
MqttProperties.setResponseTopic() cannot accept null

### ISSUE THREAD

**Issue by dennynguyen** [eclipse-paho/paho.mqtt.java#550]
Please fill out the form below before submitting, thank you!

- [ ] Bug exists Release Version 1.2.0 ( Master Branch)
- [ ] Bug exists in MQTTv3 Client on Snapshot Version 1.2.1-SNAPSHOT (Develop Branch)
- [x] Bug exists in MQTTv5 Client on Snapshot Version 1.2.1-SNAPSHOT (Develop Branch)

If this is a bug regarding the Android Service, please raise the bug here instead: https://github.com/eclipse/paho.mqtt.android/issues/new

When passing null to MqttProperties.setResponseTopic, it throws null pointer exception.

It should be acceptable to set the property to null.

```
java.lang.NullPointerException
java.lang.NullPointerException
  at org.eclipse.paho.mqttv5.common.util.MqttTopicValidator.validate(MqttTopicValidator.java:55)
  at org.eclipse.paho.mqttv5.common.packet.MqttProperties.setResponseTopic(MqttProperties.java:1229)
  at com.ibm.ism.ws.test.MyMessage.setResponseTopic(MyMessage.java:816)
  at com.ibm.ism.ws.test.CreateMessageAction.invokeApi(CreateMessageAction.java:159)
  at com.ibm.ism.ws.test.ApiCallAction.run(ApiCallAction.java:159)
  at com.ibm.ism.ws.test.Action.execute(Action.java:256)
  at com.ibm.ism.ws.test.CompositeAction$CompositeActionRunable.run(CompositeAction.java:189)
  at java.lang.Thread.run(Thread.java:745)
```

**Comment by jpwsutton** [comment]
Thanks for raising this @dennynguyen, this has now been resolved in commit efdba4a98947a7fa7fb76b5b17e8dc69f5491f87
