### ISSUE TITLE
ClassCastException when disconnected and trying to subscribe

### ISSUE THREAD

**Issue by Legion2** [eclipse-paho/paho.mqtt.java#606]
Please fill out the form below before submitting, thank you!

- [x] Bug exists Release Version 1.2.0 ( Master Branch)
- [x] Bug exists in MQTTv3 Client on Snapshot Version 1.2.1-SNAPSHOT (Develop Branch)
- [ ] Bug exists in MQTTv5 Client on Snapshot Version 1.2.1-SNAPSHOT (Develop Branch)

Client is not connected and tried to subscribe to a topic.
Version 1.2.0:
```
java.lang.ClassCastException: org.eclipse.paho.client.mqttv3.internal.wire.MqttSubscribe cannot be cast to org.eclipse.paho.client.mqttv3.internal.wire.MqttPublish
	at org.eclipse.paho.client.mqttv3.internal.ClientState.persistBufferedMessage(ClientState.java:583)
	at org.eclipse.paho.client.mqttv3.internal.ClientComms.sendNoWait(ClientComms.java:193)
	at org.eclipse.paho.client.mqttv3.MqttAsyncClient.subscribe(MqttAsyncClient.java:1091)
	at org.eclipse.paho.client.mqttv3.MqttAsyncClient.subscribe(MqttAsyncClient.java:1025)
```

MQTTv3 Version 1.2.1-SNAPSHOT:
```
java.lang.ClassCastException: org.eclipse.paho.client.mqttv3.internal.wire.MqttSubscribe cannot be cast to org.eclipse.paho.client.mqttv3.internal.wire.MqttPublish
	at org.eclipse.paho.client.mqttv3.internal.ClientState.persistBufferedMessage(ClientState.java:593)
	at org.eclipse.paho.client.mqttv3.internal.ClientComms.sendNoWait(ClientComms.java:197)
	at org.eclipse.paho.client.mqttv3.MqttAsyncClient.subscribeBase(MqttAsyncClient.java:964)
	at org.eclipse.paho.client.mqttv3.MqttAsyncClient.subscribe(MqttAsyncClient.java:937)
	at org.eclipse.paho.client.mqttv3.MqttAsyncClient.subscribe(MqttAsyncClient.java:893)
```

Client options:
```
DisconnectedBufferOptions disconnectedBufferOptions = new DisconnectedBufferOptions();
disconnectedBufferOptions.setBufferEnabled(true);
disconnectedBufferOptions.setPersistBuffer(true);
disconnectedBufferOptions.setBufferSize(10000);
disconnectedBufferOptions.setDeleteOldestMessages(false);

MqttConnectOptions options = new MqttConnectOptions();
options.setCleanSession(false);
options.setConnectionTimeout(2);
options.setKeepAliveInterval(5);
options.setAutomaticReconnect(true);
```

**Comment by icraggs** [comment]
Ok. I think that the only operation that is currently allowed while disconnected is a publish.  But we should catch it at the time the subscribe is called if that's the case.  I'll look into seeing if we can allow a subscribe to be made too.
