### ISSUE TITLE
MqttAsyncClient trying to reconnect after explicitly disconnected

### ISSUE THREAD

**Issue by junquero** [eclipse-paho/paho.mqtt.java#632]
Please fill out the form below before submitting, thank you!

- [X ] Bug exists Release Version 1.2.0 ( Master Branch)
- [X] Bug exists in MQTTv3 Client on Snapshot Version 1.2.1-SNAPSHOT (Develop Branch)
- [ ] Bug exists in MQTTv5 Client on Snapshot Version 1.2.1-SNAPSHOT (Develop Branch)

If a MqttAsyncClient is created **with reconnect option** and after used, it is closed with **disconnectForcibly**, an exception is thrown because it is trying to reconnect. 

13:16:19,196 FINE  [org.eclipse.paho.client.mqttv3.MqttAsyncClient] (Timer-11) 046aea33-627e-43f3-900b-72f5ae05b98d: exception: Client is closed (32111)
	at org.eclipse.paho.client.mqttv3.MqttAsyncClient.connect(MqttAsyncClient.java:608)
	at org.eclipse.paho.client.mqttv3.MqttAsyncClient.attemptReconnect(MqttAsyncClient.java:1177)
	at org.eclipse.paho.client.mqttv3.MqttAsyncClient.access$2(MqttAsyncClient.java:1172)
	at org.eclipse.paho.client.mqttv3.MqttAsyncClient$ReconnectTask.run(MqttAsyncClient.java:1253)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)

My expectation is that this client should try to reconnect if and only if is has been unexpectedly disconnected, but if it has been explicitly disconnected, it shouldn't try to reconnect.

I have tried with version 1.1.1, but looking at the source code, the issue is still present in latest code, because 

comms.setReconnectCallback(new MqttReconnectCallback(automaticReconnect));

has no way to "unset" the reconnect callback after created.

**Comment by Legion2** [comment]
Can not disconnect while reconnecting. It throw an exception:
```
org.eclipse.paho.client.mqttv3.MqttException: Verbindung zu Client ist getrennt
	at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:31)
	at org.eclipse.paho.client.mqttv3.internal.ClientComms.disconnect(ClientComms.java:489)
	at org.eclipse.paho.client.mqttv3.MqttAsyncClient.disconnect(MqttAsyncClient.java:826)
	at org.eclipse.paho.client.mqttv3.MqttAsyncClient.disconnect(MqttAsyncClient.java:805)
```

How can you detect the reconnecting state and stop it?

**Comment by junquero** [comment]
Use disconnectForcibly to avoid MqttException.

**Comment by Legion2** [comment]
Is there any callback for the reconnect event?
For the disconnect/connection lost event there is the `MqttCallback.connectionLost`

**Comment by junquero** [comment]
Not sure. I think there isn't any callback for reconnect event. But not 100% sure. 
I looked at the source code two weeks ago...
