### ISSUE TITLE
Seeing MqttException (0) - java.net.SocketException: Already connected after ssl handshake

### ISSUE THREAD

**Issue by AndrewJudson** [eclipse-paho/paho.mqtt.java#665]
I am supplying a custom SSLSocketFactory in order to use an http proxy.  When I create the SSLSocket, I am able to successfully CONNECT to the proxy and do SSL handshake with the server. However, paho then gives me 
MqttException (0) - java.net.SocketException: Already connected
Caused by: java.net.SocketException: Already connected
	at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:277)
	at org.eclipse.paho.client.mqttv3.internal.TCPNetworkModule.start(TCPNetworkModule.java:70)
	at org.eclipse.paho.client.mqttv3.internal.SSLNetworkModule.start(SSLNetworkModule.java:86)
	at org.eclipse.paho.client.mqttv3.internal.websocket.WebSocketSecureNetworkModule.start(WebSocketSecureNetworkModule.java:75)
	at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:650)

For reference, I am using the code from this issue https://github.com/eclipse/paho.mqtt.java/issues/575 for the SslSocketFactory implementation.

- [ ] Bug exists Release Version 1.2.0 ( Master Branch)

**Comment by onkariwaligunje** [comment]
@AndrewJudson : I am also facing same issue. Have you got any solution for this?

**Comment by Scurt123** [comment]
Do you have any solutions？
