### ISSUE TITLE
I have the following problems when upgrading from 1.2.0 to 1.2.1 or 1.2.2

### ISSUE THREAD

**Issue by lyongchang1018** [eclipse-paho/paho.mqtt.java#724]
Exception in thread "MQTT Rec: 6qm61dc96xd770g9xs" java.lang.IllegalArgumentException: Invalid UTF-8 char: [a]
	at org.eclipse.paho.client.mqttv3.internal.wire.MqttWireMessage.validateUTF8String(MqttWireMessage.java:407)
	at org.eclipse.paho.client.mqttv3.internal.wire.MqttWireMessage.decodeUTF8(MqttWireMessage.java:365)
	at org.eclipse.paho.client.mqttv3.internal.wire.MqttPublish.<init>(MqttPublish.java:64)
	at org.eclipse.paho.client.mqttv3.internal.wire.MqttWireMessage.createWireMessage(MqttWireMessage.java:207)
	at org.eclipse.paho.client.mqttv3.internal.wire.MqttWireMessage.createWireMessage(MqttWireMessage.java:182)
	at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:119)
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:136)
	at java.lang.Thread.run(Thread.java:748)

**Comment by rdasgupt** [comment]
@lyongchang1018 
Code base has changed significantly, from 1.2.0 to 1.2.2
Could you give some information about publish payload? A sample payload will help.

**Comment by silh** [comment]
We have the similar problem in 1.2.2 and probably the topic is incorrect, but another problem with that is this exception is not handled and not logged properly therefor it is very hard to track down what is going on. In our case we just saw messages about connection failing by timeout. Probably it should be handled in org.eclipse.paho.client.mqttv3.internal.CommsReceiver#run method?
Stacktrace:
```
java: Exception in thread "MQTT Rec: service-f7bee955-6130-4add-b0f7-65312619d43b" java.lang.IllegalArgumentException: Invalid UTF-8 char: [db40]
java: at org.eclipse.paho.client.mqttv3.internal.wire.MqttWireMessage.validateUTF8String(MqttWireMessage.java:407)
java: at org.eclipse.paho.client.mqttv3.internal.wire.MqttWireMessage.decodeUTF8(MqttWireMessage.java:365)
java: at org.eclipse.paho.client.mqttv3.internal.wire.MqttPublish.<init>(MqttPublish.java:64)
java: at org.eclipse.paho.client.mqttv3.internal.wire.MqttWireMessage.createWireMessage(MqttWireMessage.java:207)
java: at org.eclipse.paho.client.mqttv3.internal.wire.MqttWireMessage.createWireMessage(MqttWireMessage.java:182)
java: at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:119)
java: at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:137)
java: at java.base/java.lang.Thread.run(Thread.java:834)
```
