### ISSUE TITLE
client.disconnect() causes a crash every time - How to disconnect?

### ISSUE THREAD

**Issue by Ryanauger95** [eclipse-paho/paho.mqtt.java#739]
- [x] Bug exists Release Version 1.2.2 ( Master Branch)
- [ ] Bug exists in MQTTv3 Client on Snapshot Version 1.2.3-SNAPSHOT (Develop Branch)
- [ ] Bug exists in MQTTv5 Client on Snapshot Version 1.2.3-SNAPSHOT (Develop Branch)
I am disconnecting like this:

```
try {
            for (i in topicList.indices) {
                client!!.unsubscribe(topicList[i])
            }
            client!!.disconnect()
        } catch (e: Exception) {
            LOG.e("Could not unsubscribe!", e)
        }
```

This causes the crash below:
```
E/ActivityThread: Service <myapp>.common.notifications.NotificationService has leaked ServiceConnection org.eclipse.paho.android.service.MqttAndroidClient$MyServiceConnection@4dfe296 that was originally bound here
    android.app.ServiceConnectionLeaked: Service 
<myapp>.common.notifications.NotificationService has leaked ServiceConnection org.eclipse.paho.android.service.MqttAndroidClient$MyServiceConnection@4dfe296 that was originally bound here
        at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:1077)
        at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:971)
        at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1791)
        at android.app.ContextImpl.bindService(ContextImpl.java:1774)
        at android.content.ContextWrapper.bindService(ContextWrapper.java:539)
        at org.eclipse.paho.android.service.MqttAndroidClient.connect(MqttAndroidClient.java:425)
        at <myapp>.common.notifications.NotificationService.connect(NotificationService.kt:112)
        at <myapp>.common.notifications.NotificationService.onCreate(NotificationService.kt:49)
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:2781)
        at android.app.ActivityThread.access$1800(ActivityThread.java:151)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1402)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5280)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:963)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:758)

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: <myapp>, PID: 4251
    java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter cause
        at <myapp>.common.notifications.NotificationService.connectionLost(NotificationService.kt)
        at org.eclipse.paho.android.service.MqttAndroidClient.disconnected(MqttAndroidClient.java:1456)
        at org.eclipse.paho.android.service.MqttAndroidClient.onReceive(MqttAndroidClient.java:1393)
        at androidx.localbroadcastmanager.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:313)
        at androidx.localbroadcastmanager.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:121)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5280)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:963)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:758)
```

If I add
```client!!.unregisterResources()```
after unsubscribe, the crash doesn't happen. Is this going to cause unintended consequences? What is the proper way to disconnect?

**Comment by rdasgupt** [comment]
@Ryanauger95 
Looks like you are using paho.mqtt.android and not paho.mqtt.java.
The  unregisterResource() method is in paho.mqtt.android.
Please open your issue in paho.mqtt.android
