### ISSUE TITLE
Add Javadoc and Source jars to Maven Repository

### ISSUE THREAD

**Issue by jpwsutton** [eclipse-paho/paho.mqtt.java#78]
migrated from Bugzilla [#442927](https://bugs.eclipse.org/bugs/show_bug.cgi?id=442927)
status ASSIGNED severity _normal_ in component _MQTT-Java_ for _1.1_
Reported in version _1.0_ on platform _All_
Assigned to: Ian Craggs

On 2014-08-29 18:00:45 -0400, Obermaier Dominik wrote:

> At the moment no sources and Javadocs can be downloaded via Maven for the 1.0.0 Release and the current 1.0.1 Snapshots. The build should automatically generate these artifacts and they should be uploaded to the Maven repository as part of the release process.
> 
> This would help new users get started quickly since they get automatic javadoc help right in the IDE and it's trivial to give people the ability to dive into the source from the IDE.

On 2015-02-18 09:48:05 -0500, Ian Craggs wrote:

> The source jars are now being built too, and are uploaded into the repo for 1.0.3 onwards.  Unfortunately I hadn't updated the job when I succeeded in uploading the 1.0.2 artifacts, so the source jar is not included for 1.0.2.  I have tried building just the source jars and uploading them but haven't hit on the right combination of goals yet for the tycho-document-bundle-plugin to achieve that.  Source archives will be available in the git repo once its tagged.
> 
> I haven't succeeded in getting Javadoc jars packaged and deployed.  Using the maven-javadoc-plugin with the eclipse-jarsigner-plugin results in the following exception:
> 
> [ERROR] Failed to execute goal org.eclipse.tycho:tycho-p2-plugin:0.20.0:p2-metadata (p2-metadata) on project org.eclipse.paho.client.mqttv3: Execution p2-metadata of goal org.eclipse.tycho:tycho-p2-plugin:0.20.0:p2-metadata failed. IllegalArgumentException -> [Help 1]
> org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.eclipse.tycho:tycho-p2-plugin:0.20.0:p2-metadata (p2-metadata) on project org.eclipse.paho.client.mqttv3: Execution p2-metadata of goal org.eclipse.tycho:tycho-p2-plugin:0.20.0:p2-metadata failed.
>   at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:225)
>   at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
>   at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
>   at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
>   at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
>   at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
>   at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
>   at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
>   at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
>   at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
>   at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
>   at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
>   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
>   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
>   at java.lang.reflect.Method.invoke(Method.java:597)
>   at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
>   at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
>   at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
>   at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
> Caused by: org.apache.maven.plugin.PluginExecutionException: Execution p2-metadata of goal org.eclipse.tycho:tycho-p2-plugin:0.20.0:p2-metadata failed.
>   at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:110)
>   at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
>   ... 19 more
> Caused by: java.lang.IllegalArgumentException
>   at org.eclipse.tycho.p2.impl.publisher.P2GeneratorImpl.getCanonicalArtifact(P2GeneratorImpl.java:156)
>   at org.eclipse.tycho.p2.impl.publisher.P2GeneratorImpl.generateMetadata(P2GeneratorImpl.java:109)
>   at org.eclipse.tycho.plugins.p2.P2MetadataMojo.attachP2Metadata(P2MetadataMojo.java:145)
>   at org.eclipse.tycho.plugins.p2.P2MetadataMojo.execute(P2MetadataMojo.java:106)
>   at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
>   ... 20 more
> 
> Using the tycho-document-bundle-plugin in a simple configuration similar to the maven plugin results in no source files being found.  My attempts to pass java options such as
> 
> -sourcepath src/main/java:src/main/java-templates org.eclipse.paho.client.mqttv3
> 
>  to this plugin so far have not worked.  Google searches to find solutions to this configuration problem have hinted at solutions but nothing really conclusive.
> 
>  Any advice or help with the javadoc problem is welcome!

On 2015-02-18 09:49:20 -0500, Ian Craggs wrote:

> Assigning to myself.

**Comment by jpwsutton** [comment]
Ran into the same problem as Ian here, strangely after the changes that I made, the Javadoc compilation worked and there was no tycho p2 error on my machine, however the Hudson build had the same problem as before. I will look at a way of manually uploading the Javadoc Jars for the Released version when possible. And then look at resolving the tycho error for the next milestone.

**Comment by jpwsutton** [comment]
This is now resolved, I've implemented a second build that is triggered upon dev-nightly completing successfully. The second build then builds and deploys ONLY the documentation.
