### ISSUE TITLE
Warning when using cpaho client 1.2.5 MQTT 3.1x implementation

### ISSUE THREAD

**Issue by jayjupdhig** [eclipse-paho/paho.mqtt.java#808]
```
URL: tcp://192.168.30.247:1883
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.eclipse.paho.client.mqttv3.internal.FileLock (file:/C:/Users/xxxx/Desktop/Eclipse%20Workspaces/eclipse-jee-2020-06-R-win32-x86_64/sonoffMQTTExample/lib/paho-mqqttclient/org.eclipse.paho.client.mqttv3-1.2.5/org.eclipse.paho.client.mqttv3-1.2.5.jar) to method sun.nio.ch.FileLockImpl.release()
WARNING: Please consider reporting this to the maintainers of org.eclipse.paho.client.mqttv3.internal.FileLock
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

```

Code:

```
import java.util.UUID;

import org.eclipse.paho.client.mqttv3.MqttClient;
import org.eclipse.paho.client.mqttv3.MqttConnectOptions;

public class SonoffMqttPahoClientFacade implements MqttFacadeInterface {

	private volatile MqttClient mMqttClient = null;

	static {

	}

	private SonoffMqttPahoClientFacade() {
		super();
	}

	@Override
	public void publish(String aHost, final boolean caUseEmptyLoginDataInsteadOfNone, String aUsername,
			String aPassword, String aIdentifier, int aPort, final String caTopic, String aEncoding, String aPayload,
			final int caQOS, final boolean caRetained) throws Exception {

		if (aHost == null) {
			aHost = "localhost";
		}

		if (aUsername == null) {
			aUsername = "";
		}

		if (aPassword == null) {
			aPassword = "";
		}

		if ((aIdentifier == null) || (aIdentifier == "")) {
			aIdentifier = UUID.randomUUID().toString();
		}

		if (aPort <= 0) {
			aPort = 1883;
		}

		if ((aEncoding == null) || (aEncoding == "")) {
			aEncoding = "utf-8";
		}

		if (aPayload == null) {
			aPayload = "";
		}

		if (aPayload != "") {
			aPayload = aPayload.toUpperCase();
		}

		final String clMqttUrl = "tcp://" + aHost + ":" + aPort;

		System.out.println("URL: " + clMqttUrl);

		this.mMqttClient = new MqttClient(clMqttUrl, aIdentifier);
		final MqttConnectOptions options = new MqttConnectOptions();
		options.setAutomaticReconnect(true);
		options.setCleanSession(true);
		options.setConnectionTimeout(10);
		this.mMqttClient.connect(options);
		this.mMqttClient.publish(caTopic, aPayload.getBytes(aEncoding), caQOS, caRetained);
	}

	@Override
	public void closeConnection(final Object caClient) {
		if (caClient instanceof MqttClient) {
			final MqttClient clMqttClient = (MqttClient) caClient;
			if (clMqttClient != null) {
				Exception lException = null;
				try {
					clMqttClient.disconnect();
					clMqttClient.close();
					System.out.println("Connection was closed");
				} catch (final Exception clException) {
					lException = clException;
				} finally {
					if (lException != null) {
						final Runtime clRuntime = Runtime.getRuntime();
						clRuntime.gc();
					}
				}
			}
		}
	}

	public static SonoffMqttPahoClientFacade createInstance() {
		return new SonoffMqttPahoClientFacade();
	}

	@Override
	public Object getConnection() {
		return this.mMqttClient;
	}
}
```

So why and what's the solution for?

Thx for feedback,
Jan

**Comment by jayjupdhig** [comment]
It works, but the warnings are strange...

**Comment by jayjupdhig** [comment]
No, it works not always. Sometime it works, sometime not. code:

```
URL: tcp://192.168.30.247:1883
Exception in thread "main" MqttException (0)
	at org.eclipse.paho.client.mqttv3.persist.MqttDefaultFilePersistence.restoreBackups(MqttDefaultFilePersistence.java:280)
	at org.eclipse.paho.client.mqttv3.persist.MqttDefaultFilePersistence.open(MqttDefaultFilePersistence.java:130)
	at org.eclipse.paho.client.mqttv3.internal.ConnectActionListener.connect(ConnectActionListener.java:174)
	at org.eclipse.paho.client.mqttv3.internal.ConnectActionListener.onFailure(ConnectActionListener.java:137)
	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.fireActionEvent(CommsCallback.java:338)
	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.handleActionComplete(CommsCallback.java:272)
	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.asyncOperationComplete(CommsCallback.java:460)
	at org.eclipse.paho.client.mqttv3.internal.ClientComms.shutdownConnection(ClientComms.java:436)
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:184)
	at java.base/java.lang.Thread.run(Thread.java:832)

```


Have a fix for??

**Comment by jayjupdhig** [comment]
Here is crashes sometimes. It's like a random generator!! ;-)

```
this.mMqttClient.connect(options);
		System.exit(0);
```


Last line is for debug!!!

**Comment by jayjupdhig** [comment]
i saw a .lck file in a folder created by your lib that caused that issue. What's the reason and how to avoid it?

**Comment by jayjupdhig** [comment]
-> The warnings are not in relation with that .lck files.

Now i saw that i used a wrong clientID (equivalent to an other device). Now i use a random-UUID-generated clientID and the problem with the .lck-files seems to be gone.

But these messages are still present:

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.eclipse.paho.client.mqttv3.internal.FileLock (file:/C:/Users/xxxx/Desktop/Eclipse%20Workspaces/eclipse-jee-2020-06-R-win32-x86_64/sonoffMQTTExample/lib/paho-mqqttclient/org.eclipse.paho.client.mqttv3-1.2.5/org.eclipse.paho.client.mqttv3-1.2.5.jar) to method sun.nio.ch.FileLockImpl.release()
WARNING: Please consider reporting this to the maintainers of org.eclipse.paho.client.mqttv3.internal.FileLock
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

To suppress them, i used that workaround, witch is useable for a standard java application with main funktion, the static constructor will be called one when the app starts:

```
private static final boolean cmSuppressErrorLogger = true;

    static {
        if (RabbitMqTestBoth.cmSuppressErrorLogger) {
            System.err.close();
            OutputStream lFileOutputStream = null;
            PrintStream lPrintStream = null;

            try {
                lFileOutputStream = new FileOutputStream("NUL:");
                lPrintStream = new PrintStream(lFileOutputStream);
                System.setErr(lPrintStream);
            } catch (final Exception clException) {
                final Runtime clRuntime = Runtime.getRuntime();
                clRuntime.gc();
            } finally {
                Exception lException = null;
                if (lPrintStream != null) {
                    try {
                        lPrintStream.close();
                    } catch (final Exception clException) {
                        lException = clException;
                    } finally {
                        if (lException != null) {
                            final Runtime clRuntime = Runtime.getRuntime();
                            clRuntime.gc();
                        }
                    }
                }

                lException = null;

                if (lFileOutputStream != null) {
                    try {
                        lFileOutputStream.close();
                    } catch (final Exception clException) {
                        lException = clException;
                    } finally {
                        if (lException != null) {
                            final Runtime clRuntime = Runtime.getRuntime();
                            clRuntime.gc();
                        }
                    }
                }
            }
        }
    }
```


And then, turn i on again in the constructor after loading the constructor AFTER loading the code that causes that warnings:

```
private MyClass(final String[] caArgArr) throws Exception {
        super();
        ...
...
...

System.setErr(System.err);
```

**Comment by jayjupdhig** [comment]
No idea? Is that question too complex for that place here?

**Comment by rdasgupt** [comment]
We will check this out and respond back ASAP.

**Comment by rdasgupt** [comment]
Duplicate of #794

**Comment by jayjupdhig** [comment]
"Duplicate of #794"

Thanks, so i will close it now! :-)
