### ISSUE TITLE
Crash at WebSocketFrame class by ArrayIndexOutOfBoundsException in an InputStream read attempt

### ISSUE THREAD

**Issue by natanvotre** [eclipse-paho/paho.mqtt.java#835]
I am having this issue happening on my app sometimes. The current rate is 4 times by month.

```
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: length=119776; regionStart=-1; regionLength=119777
       at com.android.org.conscrypt.ArrayUtils.checkOffsetAndCount(ArrayUtils.java:32)
       at com.android.org.conscrypt.ConscryptFileDescriptorSocket$SSLInputStream.read(ConscryptFileDescriptorSocket.java:533)
       at org.eclipse.paho.client.mqttv3.internal.websocket.WebSocketFrame.<init>(WebSocketFrame.java:169)
       at org.eclipse.paho.client.mqttv3.internal.websocket.WebSocketReceiver.run(WebSocketReceiver.java:103)
       at java.lang.Thread.run(Thread.java:919) 
```

The `inputStream` might be linked into an `outputStream` as suggested by [this issue](https://stackoverflow.com/questions/19653511/indexoutofboundsexception-when-reading-from-stream)..

Can you guys help me with that?

**Comment by mayankzen123** [comment]
Facing similar issue

```
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: length=16757; regionStart=-1; regionLength=16758
       at com.android.org.conscrypt.ArrayUtils.checkOffsetAndCount(ArrayUtils.java:32)
       at com.android.org.conscrypt.ConscryptFileDescriptorSocket$SSLInputStream.read(ConscryptFileDescriptorSocket.java:533)
       at org.eclipse.paho.client.mqttv3.internal.websocket.WebSocketFrame.<init>(WebSocketFrame.java:177)
       at org.eclipse.paho.client.mqttv3.internal.websocket.WebSocketReceiver.run(WebSocketReceiver.java:104)
       at java.lang.Thread.run(Thread.java:919)
```

**Comment by OleksiiRudenko-TomTom** [comment]
Having the same issue:
```
ArrayIndexOutOfBoundsException: length=3; regionStart=-1; regionLength=4
    at com.android.org.conscrypt.ArrayUtils.checkOffsetAndCount(ArrayUtils.java:32)
    at com.android.org.conscrypt.ConscryptFileDescriptorSocket$SSLInputStream.read(ConscryptFileDescriptorSocket.java:533)
    at org.eclipse.paho.client.mqttv3.internal.websocket.WebSocketFrame.<init>(WebSocketFrame.java:177)
    at org.eclipse.paho.client.mqttv3.internal.websocket.WebSocketReceiver.run(WebSocketReceiver.java:0)
    at org.eclipse.paho.client.mqttv3.internal.websocket.WebSocketReceiver.run(WebSocketReceiver.java:104)
```
WebSocketFrame constructor doesn't handle properly the case when `ConscryptFileDescriptorSocket.read` returns -1, so that `offsetIndex` becomes negative and `tempLength` increases out of buffer length

**Comment by oleksii-rudenko** [comment]
Having the same issue:

```
ArrayIndexOutOfBoundsException: length=3; regionStart=-1; regionLength=4
    at com.android.org.conscrypt.ArrayUtils.checkOffsetAndCount(ArrayUtils.java:32)
    at com.android.org.conscrypt.ConscryptFileDescriptorSocket$SSLInputStream.read(ConscryptFileDescriptorSocket.java:533)
    at org.eclipse.paho.client.mqttv3.internal.websocket.WebSocketFrame.<init>(WebSocketFrame.java:177)
    at org.eclipse.paho.client.mqttv3.internal.websocket.WebSocketReceiver.run(WebSocketReceiver.java:0)
    at org.eclipse.paho.client.mqttv3.internal.websocket.WebSocketReceiver.run(WebSocketReceiver.java:104)
```
WebSocketFrame constructor doesn't handle the case when ConscryptFileDescriptorSocket.SSLInputStream.read returns -1, so that `offsetIndex` becomes negative and `tempLength` increases out of buffer length
