### ISSUE TITLE
"Connection lost (32109)" occurred when publishing a large message

### ISSUE THREAD

**Issue by alumuko** [eclipse-paho/paho.mqtt.java#881]
- [x] Bug exists Release Version 1.2.5 ( Master Branch)
- [x] Bug exists in MQTTv3 Client on Snapshot Version 1.2.6-SNAPSHOT (Develop Branch)
- [ ] Bug exists in MQTTv5 Client on Snapshot Version 1.2.6-SNAPSHOT (Develop Branch)

Connection lost (32109) - java.io.EOFException occurred when publishing a large message that size is larger than 20k bytes.
But no exceptions occurred when publishing small messages that size is smaller than 1k bytes.

- I am sure that all clients ID are unique.
- Even if setting keepalive-timer = 15 seconds and connection-timeout = 30 seconds, Connection lost (32109) has occurred yet.
- Using SSL connection.

Stacktrace of Version 1.2.5:
> 接続喪失 (32109) - java.io.EOFException
>         at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:197)
>         at java.lang.Thread.run(Thread.java:748)
> Caused by: java.io.EOFException
>         at java.io.DataInputStream.readByte(DataInputStream.java:267)
>         at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:92)
>         at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:137)

**Comment by alumuko** [comment]
additonal information:

- The exception occured when sending a message to a mosquitto MQTT Broker ver 1.6.9.
 but the exception did not occured when sending same message to a mosquitto MQTT Broker ver 1.6.7.

**Comment by alumuko** [comment]
The exception did not occurred when sending a message to the latest mosquitto MQTT Broker , ver 2.0.11 .
So I think it's a MQTT Broker problem and had already been fixed.
