### ISSUE TITLE
use harmony，a wrong

### ISSUE THREAD

**Issue by CareyLiu** [eclipse-paho/paho.mqtt.java#906]
Please fill out the form below before submitting, thank you!

- [x] Bug exists Release Version 1.2.0 ( Master Branch)
- [x] Bug exists in MQTTv3 Client on Snapshot Version 1.2.6-SNAPSHOT (Develop Branch)

11-30 11:24:50.408 1074-1278/? E HiEvent : java.lang.ExceptionInInitializerError
11-30 11:24:50.408 1074-1278/? E HiEvent : 	at org.eclipse.paho.client.mqttv3.MqttClient.<init>(MqttClient.java:229)
11-30 11:24:50.408 1074-1278/? E HiEvent : 	at com.sd.fn_jiareqi.mqtt.ClientMQTT.start(ClientMQTT.java:21)
11-30 11:24:50.408 1074-1278/? E HiEvent : 	at com.sd.fn_jiareqi.slice.MainAbilitySlice.onStart(MainAbilitySlice.java:51)
11-30 11:24:50.408 1074-1278/? E HiEvent : 	at ohos.aafwk.ability.AbilitySlice.start(AbilitySlice.java:3270)
11-30 11:24:50.408 1074-1278/? E HiEvent : 	at ohos.aafwk.ability.AbilitySliceScheduler.handleStartAbilitySlice(AbilitySliceScheduler.java:717)
11-30 11:24:50.408 1074-1278/? E HiEvent : 	at ohos.aafwk.ability.AbilitySliceManager.onAbilityStart(AbilitySliceManager.java:300)
11-30 11:24:50.408 1074-1278/? E HiEvent : 	at ohos.aafwk.ability.Ability.dispatchAbilityLifecycle(Ability.java:4579)
11-30 11:24:50.408 1074-1278/? E HiEvent : 	at ohos.aafwk.ability.Ability.start(Ability.java:3634)
11-30 11:24:50.408 1074-1278/? E HiEvent : 	at ohos.aafwk.ability.Ability.handleLifecycleTransaction(Ability.java:4751)
11-30 11:24:50.408 1074-1278/? E HiEvent : 	at ohos.aafwk.ability.Ability.scheduleAbilityLifecycle(Ability.java:1517)
11-30 11:24:50.408 1074-1278/? E HiEvent : 	at ohos.abilityshell.AbilityShellDelegate.scheduleAbilityLifecycle(AbilityShellDelegate.java:132)
11-30 11:24:50.408 1074-1278/? E HiEvent : 	at ohos.abilityshell.AbilityShellActivityDelegate.onStart(AbilityShellActivityDelegate.java:340)
11-30 11:24:50.408 1074-1278/? E HiEvent : 	at ohos.abilityshel

help me，thank u

**Comment by CareyLiu** [comment]
MqttClient client = new MqttClient(HOST, clientid, new MemoryPersistence());

**Comment by CareyLiu** [comment]
java.util.MissingResourceException: Can't find bundle for base name org.eclipse.paho.client.mqttv3.internal.nls.logcat, locale zh_CN_#Hans

**Comment by CareyLiu** [comment]
use 1.2.5 

java.util.MissingResourceException: Can't find bundle for base name org.eclipse.paho.client.mqttv3.internal.nls.logcat, locale zh_CN_#Hans
12-01 10:32:19.468 17651-17651/? E AndroidRuntime: 	at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1561)
12-01 10:32:19.468 17651-17651/? E AndroidRuntime: 	at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1384)
12-01 10:32:19.468 17651-17651/? E AndroidRuntime: 	at java.util.ResourceBundle.getBundle(ResourceBundle.java:771)
12-01 10:32:19.468 17651-17651/? E AndroidRuntime: 	at org.eclipse.paho.client.mqttv3.logging.LoggerFactory.getLogger(LoggerFactory.java:72)
12-01 10:32:19.468 17651-17651/? E AndroidRuntime: 	at org.eclipse.paho.client.mqttv3.TimerPingSender.<init>(TimerPingSender.java:34)
12-01 10:32:19.468 17651-17651/? E AndroidRuntime: 	at org.eclipse.paho.client.mqttv3.MqttAsyncClient.<init>(MqttAsyncClient.java:317)
12-01 10:32:19.468 17651-17651/? E AndroidRuntime: 	at org.eclipse.paho.client.mqttv3.MqttClient.<init>(MqttClient.java:227)
12-01 10:32:19.468 17651-17651/? E AndroidRuntime: 	at com.sd.fn_jiareqi.mqtt.ClientMQTT.start(ClientMQTT.java:17)
12-01 10:32:19.468 17651-17651/? E AndroidRuntime: 	at com.sd.fn_jiareqi.slice.MainAbilitySlice.onStart(MainAbilitySlice.java:57)
12-01 10:32:19.468 17651-17651/? E AndroidRuntime: 	at ohos.aafwk.ability.AbilitySlice.start(AbilitySlice.java:3270)
12-01 10:32:19.468 17651-17651/? E AndroidRuntime: 	at ohos.aafwk.ability.AbilitySliceScheduler.handleStartAbilitySlice(AbilitySliceScheduler.java:717)
12-01 10:32:19.468 17651-17651/? E AndroidRuntime: 	at ohos.aafwk.ability.AbilitySliceManager.onAbilityStart(AbilitySliceManager.java:300)
12-01 10:32:19.468 17651-17651/? E AndroidRuntime: 	at ohos.aafwk.ability.Ability.dispatchAbilityLifecycle(Ability.java:4579)
12-01 10:32:19.468 17651-17651/? E AndroidRuntime: 	at ohos.aafwk.ability.Ability.start(Ability.java:3634)
12-01 10:32:19.468 17651-17651/? E AndroidRuntime: 	at ohos.aafwk.ability.Ability.handleLifecycleTransaction(Ability.java:4751)
12-01 10:32:19.468 17651-17651/? E AndroidRuntime: 	at ohos.aafwk.ability.Ability.scheduleAbilityLifecycle(Ability.java:1517)
12-01 10:32:19.468 17651-17651/? E AndroidRuntime: 	at ohos.abilityshell.AbilityShellDelegate.scheduleAbilityLifecycle(AbilityShellDelegate.java:132)
12-01 10:32:19.468 17651-17651/? E AndroidRuntime: 	at ohos.abilityshell.AbilityShellActivityDelegate.onStart(AbilityShellActivityDelegate.java:340)
12-01 10:32:19.468 17651-17651/? E AndroidRuntime: 	at ohos.abilityshell.AbilityShellActivity.onStart(AbilityShellActivity.java:67)
12-01 10:32:19.468 17651-17651/? E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1447)
12-01 10:32:19.468 17651-17651/? E AndroidRuntime: 	at android.app.Activity.performStart(Activity.java:8237)
12-01 10:32:19.468 17651-17651/? E AndroidRuntime: 	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:4084)
12-01 10:32:19.468 17651-17651/? E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:235)
12-01 10:32:19.468 17651-17651/? E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:215)
12-01 10:32:19.468 17651-17651/? E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:187)
12-01 10:32:19.468 17651-17651/? E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:105)
12-01 10:32:19.468 17651-17651/? E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2613)
12-01 10:32:19.468 17651-17651/? E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:110)
12-01 10:32:19.468 17651-17651/? E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:219)
12-01 10:32:19.468 17651-17651/? E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8668)
12-01 10:32:19.468 17651-17651/? E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-01 10:32:19.468 17651-17651/? E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
12-01 10:32:19.468 17651-17651/? E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)

**Comment by CareyLiu** [comment]
help me
