### ISSUE TITLE
v5 1.2.5 subscript method self calling

### ISSUE THREAD

**Issue by ElisaMin** [eclipse-paho/paho.mqtt.java#917]
```
java.lang.StackOverflowError
	at org.eclipse.paho.mqttv5.client.MqttClient.subscribe(MqttClient.java:525)
	at org.eclipse.paho.mqttv5.client.MqttClient.subscribe(MqttClient.java:525)
	at org.eclipse.paho.mqttv5.client.MqttClient.subscribe(MqttClient.java:525)
	at org.eclipse.paho.mqttv5.client.MqttClient.subscribe(MqttClient.java:525)
	at org.eclipse.paho.mqttv5.client.MqttClient.subscribe(MqttClient.java:525)
	at org.eclipse.paho.mqttv5.client.MqttClient.subscribe(MqttClient.java:525)
```
- [*] Bug exists Release Version 1.2.5 ( Master Branch)

**Comment by wattsec** [comment]
It looks there is a bug in org.eclipse.paho.mqttv5.client.MqttClient where :

```
public IMqttToken subscribe(String[] topicFilters, int[] qos, IMqttMessageListener[] messageListeners) throws MqttException {
    return this.subscribe(topicFilters, qos, messageListeners);
}
```

Should be something like:

```
public IMqttToken subscribe(String[] topicFilters, int[] qos, IMqttMessageListener[] messageListeners) throws MqttException {
    IMqttToken tok = aClient.subscribe(topicFilters, qos, null, messageListeners);
    tok.waitForCompletion(getTimeToWait());
    return tok;
}
```

**Comment by inad9300** [comment]
Any chance of seeing this bug fixed?

**Comment by fnwind** [comment]
It seems this project is no longer maintained.
I encountered the same issue, but I found that using the `IMqttToken subscribe(MqttSubscription[] subscriptions, IMqttMessageListener[] messageListeners)` method can resolve this problem - at least it works for me.

```java
// Wrap subscription topics
MqttSubscription[] subscriptions = new MqttSubscription[]{
    new MqttSubscription(topicFilter, qos)
};

// Wrap message listener
IMqttMessageListener listener = (topic, mqttMessage) -> {
  // some code...
};
IMqttMessageListener[] messageListeners = new IMqttMessageListener[]{ listener };

// Finally use MqttClient instead of IMqttClient to subscribe
MqttClient client = new MqttClient(serverUri, clientId);
client.subscribe(subscriptions, messageListeners);
```
