### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.io.File.delete()' on a null object reference

### ISSUE THREAD

**Issue by seven001** [eclipse-paho/paho.mqtt.java#936]
Thread Name: 'MQTT Rec: 02fefcfee931446a8471c4303c971453'
Back traces starts.
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.io.File.delete()' on a null object reference
	at h.b.a.a.a.a0.b.clear(MqttDefaultFilePersistence.java:4)
	at org.eclipse.paho.client.mqttv3.internal.ClientState.clearState(ClientState.java:2)
	at org.eclipse.paho.client.mqttv3.internal.ClientState.notifyReceivedAck(ClientState.java:26)
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:22)
	at java.lang.Thread.run(Thread.java:920)
Back traces ends.

How to solve it?

**Comment by chlbeyond** [comment]
Brother, have you solved this problem? Please help me.
