### ISSUE TITLE
NPE invoking org.eclipse.paho.client.mqttv3.internal.HighResolutionTimer.nanoTime()

### ISSUE THREAD

**Issue by nm2n** [eclipse-paho/paho.mqtt.java#955]
- [x] Bug exists Release Version 1.2.5 ( Master Branch)
- [ ] Bug exists in MQTTv3 Client on Snapshot Version 1.2.6-SNAPSHOT (Develop Branch)
- [ ] Bug exists in MQTTv5 Client on Snapshot Version 1.2.6-SNAPSHOT (Develop Branch)

We see this rare NPE in our crash reporting tool of our Android App:

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'long org.eclipse.paho.client.mqttv3.internal.HighResolutionTimer.nanoTime()' on a null object reference
       at org.eclipse.paho.client.mqttv3.internal.ClientState.notifyReceivedMsg(ClientState.java:1083)
       at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:167)
       at java.lang.Thread.run(Thread.java:919)
```

Please note that we are not using [paho.mqtt.android](https://github.com/eclipse/paho.mqtt.android)

Some statistics that might be helpful:
* 94% of the crashes are happening in the background
* Majority of crashes happen on OnePlus and OPPO devices

**Comment by ColorfulHorse** [comment]
same problem, any progress?
