### ISSUE TITLE
MqttException: Too many publishes in progress

### ISSUE THREAD

**Issue by inspired95** [eclipse-paho/paho.mqtt.java#993]
Hello everyone!

Give you please share with me a solution for an exception
org.eclipse.paho.mqttv5.common.MqttException: Too many publishes in progress

that is available in lib MQTT v5 
org.eclipse.paho.mqttv5.client_1.2.5.jar

In MQTT v3 a method called setMaxInflight(which helps) was available in MqttConnectionOptions. In MQTT v5 it is not there anymore.

Thanks for help!

**Comment by IanBoden** [comment]
Not something I've looked at, but does the setReceiveMaximum do what you want? 

Although looking at the comments it should default to 65535 which is also the maximum so unless you are setting it to a lower value it probably wont help. I believe the maxInFlight was also limitted to 65535 so maybe I'm conflating two different settings.

**Comment by MetSystem** [comment]
The same issue.
Not set up setReceiveMaximum
```java
org.eclipse.paho.mqttv5.common.MqttException: Too many publishes in progress

	at org.eclipse.paho.mqttv5.client.internal.ClientState.send(ClientState.java:544)

	at org.eclipse.paho.mqttv5.client.internal.ClientComms.internalSend(ClientComms.java:155)

	at org.eclipse.paho.mqttv5.client.internal.ClientComms.sendNoWait(ClientComms.java:218)

	at org.eclipse.paho.mqttv5.client.MqttAsyncClient.publish(MqttAsyncClient.java:1530)

	at org.eclipse.paho.mqttv5.client.MqttClient.publish(MqttClient.java:564)
```
